# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Nims\Documents\PythonProjects\PokerHandRanking\handsRankForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_QVB = QtWidgets.QVBoxLayout()
        self.main_QVB.setSpacing(6)
        self.main_QVB.setObjectName("main_QVB")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.main_QVB.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.main_QVB.addWidget(self.label_2)
        self.buttons_hL = QtWidgets.QHBoxLayout()
        self.buttons_hL.setObjectName("buttons_hL")
        self.addCard_btn = QtWidgets.QPushButton(self.centralwidget)
        self.addCard_btn.setObjectName("addCard_btn")
        self.buttons_hL.addWidget(self.addCard_btn)
        self.removeCard_btn = QtWidgets.QPushButton(self.centralwidget)
        self.removeCard_btn.setObjectName("removeCard_btn")
        self.buttons_hL.addWidget(self.removeCard_btn)
        self.main_QVB.addLayout(self.buttons_hL)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hands_label = QtWidgets.QLabel(self.groupBox)
        self.hands_label.setObjectName("hands_label")
        self.verticalLayout.addWidget(self.hands_label)
        self.main_QVB.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.main_QVB)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Poker Hand Ranking UI"))
        self.label.setText(_translate("MainWindow", "Pick a color :"))
        self.label_2.setText(_translate("MainWindow", "Then pick a number :"))
        self.addCard_btn.setText(_translate("MainWindow", "Add Card"))
        self.removeCard_btn.setText(_translate("MainWindow", "remove selected card"))
        self.groupBox.setTitle(_translate("MainWindow", "Poker hand"))
        self.hands_label.setText(_translate("MainWindow", " "))
